import type { Product } from "./types";

export const categories = [
  { id: "smartphones", name: "Smartphones", icon: "Smartphone" },
  { id: "laptops", name: "Laptops & Computers", icon: "Laptop" },
  { id: "audio", name: "Audio & Headphones", icon: "Headphones" },
  { id: "wearables", name: "Wearables & Smartwatches", icon: "Watch" },
  { id: "tablets", name: "Tablets", icon: "Tablet" },
  { id: "cameras", name: "Cameras & Photography", icon: "Camera" },
  { id: "gaming", name: "Gaming", icon: "Gamepad2" },
  { id: "tv", name: "TVs & Displays", icon: "Tv" },
  { id: "accessories", name: "Accessories", icon: "Cable" },
];

export const brands = [
  "Samsung", "Apple", "HP", "Dell", "Sony", "JBL", "Google",
  "Lenovo", "Nikon", "Canon", "Fujifilm", "PlayStation", "Xbox",
  "Anker", "Logitech", "LG", "ASUS", "Oraimo",
];

const img = (url: string) => `${url}&fit=crop&h=600&w=600`;

export const products: Product[] = [
  // ===== SMARTPHONES =====
  {
    id: "sm-001",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    model: "SM-S928B",
    category: "smartphones",
    ram: "12GB",
    storage: "256GB",
    color: "Titanium Gray",
    price: 1250000,
    oldPrice: 1350000,
    image: img("https://images.pexels.com/photos/36680544/pexels-photo-36680544.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/36680544/pexels-photo-36680544.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
      img("https://images.pexels.com/photos/11120516/pexels-photo-11120516.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
      img("https://images.pexels.com/photos/14979013/pexels-photo-14979013.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The Samsung Galaxy S24 Ultra features a stunning 6.8-inch Dynamic AMOLED 2X display, 200MP quad-camera system with 100x Space Zoom, and the powerful Snapdragon 8 Gen 3 processor. Built-in S Pen for productivity and creativity on the go.",
    specifications: {
      "Display": "6.8\" Dynamic AMOLED 2X, 120Hz",
      "Processor": "Snapdragon 8 Gen 3",
      "RAM": "12GB",
      "Storage": "256GB",
      "Rear Camera": "200MP + 50MP + 12MP + 10MP",
      "Front Camera": "12MP",
      "Battery": "5000mAh",
      "OS": "Android 14, One UI 6.1",
      "5G": "Yes",
      "Color": "Titanium Gray",
    },
    featured: true,
    popular: true,
  },
  {
    id: "sm-002",
    name: "Samsung Galaxy A55 5G",
    brand: "Samsung",
    model: "SM-A556E",
    category: "smartphones",
    ram: "8GB",
    storage: "128GB",
    color: "Awesome Iceblue",
    price: 320000,
    image: img("https://images.pexels.com/photos/20360361/pexels-photo-20360361.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/20360361/pexels-photo-20360361.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
      img("https://images.pexels.com/photos/9403817/pexels-photo-9403817.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The Galaxy A55 5G delivers premium features at a mid-range price with a 6.6-inch Super AMOLED display, 50MP triple camera, and Exynos 1480 processor. Gorilla Glass Victus+ protection and IP67 water resistance.",
    specifications: {
      "Display": "6.6\" Super AMOLED, 120Hz",
      "Processor": "Exynos 1480",
      "RAM": "8GB",
      "Storage": "128GB",
      "Rear Camera": "50MP + 12MP + 5MP",
      "Front Camera": "32MP",
      "Battery": "5000mAh",
      "OS": "Android 14, One UI 6.1",
      "5G": "Yes",
      "Color": "Awesome Iceblue",
    },
    popular: true,
  },
  {
    id: "sm-003",
    name: "Apple iPhone 15 Pro Max",
    brand: "Apple",
    model: "A2849",
    category: "smartphones",
    ram: "8GB",
    storage: "256GB",
    color: "Natural Titanium",
    price: 1650000,
    oldPrice: 1750000,
    image: img("https://images.pexels.com/photos/30639091/pexels-photo-30639091.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/30639091/pexels-photo-30639091.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
      img("https://images.pexels.com/photos/18311092/pexels-photo-18311092.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "iPhone 15 Pro Max features a titanium design, the A17 Pro chip, and a Pro-grade camera system with a 48MP main camera. 5x Telephoto lens with the longest optical zoom ever on iPhone.",
    specifications: {
      "Display": "6.7\" Super Retina XDR, 120Hz ProMotion",
      "Processor": "A17 Pro",
      "RAM": "8GB",
      "Storage": "256GB",
      "Rear Camera": "48MP + 12MP + 12MP",
      "Front Camera": "12MP",
      "Battery": "Up to 29 hours video",
      "OS": "iOS 17",
      "5G": "Yes",
      "Color": "Natural Titanium",
    },
    featured: true,
    popular: true,
  },
  {
    id: "sm-004",
    name: "Apple iPhone 15",
    brand: "Apple",
    model: "A2882",
    category: "smartphones",
    ram: "6GB",
    storage: "128GB",
    color: "Blue",
    price: 1050000,
    image: img("https://images.pexels.com/photos/18311092/pexels-photo-18311092.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/18311092/pexels-photo-18311092.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
      img("https://images.pexels.com/photos/30639091/pexels-photo-30639091.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "iPhone 15 brings the Dynamic Island to all models, a 48MP main camera with 2x Telephoto, and USB-C. Powered by the A16 Bionic chip with a durable ceramic shield front.",
    specifications: {
      "Display": "6.1\" Super Retina XDR",
      "Processor": "A16 Bionic",
      "RAM": "6GB",
      "Storage": "128GB",
      "Rear Camera": "48MP + 12MP",
      "Front Camera": "12MP",
      "Battery": "Up to 20 hours video",
      "OS": "iOS 17",
      "5G": "Yes",
      "Color": "Blue",
    },
    popular: true,
  },
  {
    id: "sm-005",
    name: "Samsung Galaxy A15 4G",
    brand: "Samsung",
    model: "SM-A155F",
    category: "smartphones",
    ram: "4GB",
    storage: "128GB",
    color: "Blue Black",
    price: 165000,
    image: img("https://images.pexels.com/photos/9403817/pexels-photo-9403817.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/9403817/pexels-photo-9403817.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The Galaxy A15 offers a 6.5-inch Super AMOLED display, 50MP triple camera, and MediaTek Helio G99 processor. Great value with Samsung's signature display quality.",
    specifications: {
      "Display": "6.5\" Super AMOLED, 90Hz",
      "Processor": "MediaTek Helio G99",
      "RAM": "4GB",
      "Storage": "128GB",
      "Rear Camera": "50MP + 5MP + 2MP",
      "Front Camera": "13MP",
      "Battery": "5000mAh",
      "OS": "Android 14, One UI 6.1",
      "5G": "No",
      "Color": "Blue Black",
    },
  },
  {
    id: "sm-006",
    name: "Google Pixel 8 Pro",
    brand: "Google",
    model: "GP8P-256",
    category: "smartphones",
    ram: "12GB",
    storage: "256GB",
    color: "Obsidian",
    price: 980000,
    image: img("https://images.pexels.com/photos/12360229/pexels-photo-12360229.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/12360229/pexels-photo-12360229.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The Pixel 8 Pro features Google's Tensor G3 chip, a 6.7-inch LTPO OLED display, and a 50MP triple camera system with AI-powered photography. 7 years of OS and security updates.",
    specifications: {
      "Display": "6.7\" LTPO OLED, 120Hz",
      "Processor": "Google Tensor G3",
      "RAM": "12GB",
      "Storage": "256GB",
      "Rear Camera": "50MP + 48MP + 48MP",
      "Front Camera": "10.5MP",
      "Battery": "5050mAh",
      "OS": "Android 14",
      "5G": "Yes",
      "Color": "Obsidian",
    },
    new: true,
  },
  {
    id: "sm-007",
    name: "Samsung Galaxy S24 FE",
    brand: "Samsung",
    model: "SM-S721B",
    category: "smartphones",
    ram: "8GB",
    storage: "256GB",
    color: "Graphite",
    price: 680000,
    image: img("https://images.pexels.com/photos/14979013/pexels-photo-14979013.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/14979013/pexels-photo-14979013.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The Galaxy S24 FE brings flagship features to a more accessible price point with Exynos 2400e, 6.7-inch Dynamic AMOLED 2X display, and Galaxy AI features.",
    specifications: {
      "Display": "6.7\" Dynamic AMOLED 2X, 120Hz",
      "Processor": "Exynos 2400e",
      "RAM": "8GB",
      "Storage": "256GB",
      "Rear Camera": "50MP + 12MP + 8MP",
      "Front Camera": "10MP",
      "Battery": "4700mAh",
      "OS": "Android 14, One UI 6.1",
      "5G": "Yes",
      "Color": "Graphite",
    },
    new: true,
  },
  {
    id: "sm-008",
    name: "Apple iPhone 14",
    brand: "Apple",
    model: "A2881",
    category: "smartphones",
    ram: "6GB",
    storage: "128GB",
    color: "Midnight",
    price: 850000,
    oldPrice: 920000,
    image: img("https://images.pexels.com/photos/11120516/pexels-photo-11120516.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/11120516/pexels-photo-11120516.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "iPhone 14 features a 6.1-inch Super Retina XDR display, A15 Bionic chip, and an advanced dual-camera system with Photonic Engine for incredible low-light photos.",
    specifications: {
      "Display": "6.1\" Super Retina XDR",
      "Processor": "A15 Bionic",
      "RAM": "6GB",
      "Storage": "128GB",
      "Rear Camera": "12MP + 12MP",
      "Front Camera": "12MP",
      "Battery": "Up to 20 hours video",
      "OS": "iOS 17",
      "5G": "Yes",
      "Color": "Midnight",
    },
  },

  // ===== LAPTOPS =====
  {
    id: "lp-001",
    name: "HP Pavilion 15 Laptop",
    brand: "HP",
    model: "15-eh2025wm",
    category: "laptops",
    subcategory: "Business",
    ram: "8GB",
    storage: "512GB SSD",
    color: "Natural Silver",
    price: 580000,
    oldPrice: 650000,
    image: img("https://images.pexels.com/photos/35229321/pexels-photo-35229321.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/35229321/pexels-photo-35229321.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
      img("https://images.pexels.com/photos/11982694/pexels-photo-11982694.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The HP Pavilion 15 combines performance and style with an AMD Ryzen 5 processor, 15.6-inch Full HD display, and all-day battery life. Perfect for work and entertainment.",
    specifications: {
      "Display": "15.6\" Full HD IPS, 250 nits",
      "Processor": "AMD Ryzen 5 7530U",
      "RAM": "8GB DDR4",
      "Storage": "512GB NVMe SSD",
      "Graphics": "AMD Radeon Graphics",
      "Battery": "Up to 8 hours",
      "OS": "Windows 11 Home",
      "Weight": "1.75 kg",
      "Color": "Natural Silver",
    },
    featured: true,
    popular: true,
  },
  {
    id: "lp-002",
    name: "Apple MacBook Pro 14 M3",
    brand: "Apple",
    model: "MRXQ3LL/A",
    category: "laptops",
    subcategory: "Premium",
    ram: "8GB",
    storage: "512GB SSD",
    color: "Space Black",
    price: 1750000,
    image: img("https://images.pexels.com/photos/129205/pexels-photo-129205.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/129205/pexels-photo-129205.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
      img("https://images.pexels.com/photos/93405/pexels-photo-93405.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The MacBook Pro 14-inch with M3 chip delivers extraordinary performance with a Liquid Retina XDR display, up to 22 hours battery life, and pro-grade ports. Built for creative professionals.",
    specifications: {
      "Display": "14.2\" Liquid Retina XDR, ProMotion 120Hz",
      "Processor": "Apple M3 8-core",
      "RAM": "8GB Unified Memory",
      "Storage": "512GB SSD",
      "Graphics": "10-core GPU",
      "Battery": "Up to 22 hours",
      "OS": "macOS Sonoma",
      "Weight": "1.61 kg",
      "Color": "Space Black",
    },
    featured: true,
  },
  {
    id: "lp-003",
    name: "Dell Inspiron 15 3000",
    brand: "Dell",
    model: "3520-5915",
    category: "laptops",
    subcategory: "Budget",
    ram: "8GB",
    storage: "256GB SSD",
    color: "Carbon Black",
    price: 420000,
    image: img("https://images.pexels.com/photos/93405/pexels-photo-93405.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/93405/pexels-photo-93405.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The Dell Inspiron 15 3000 is a reliable everyday laptop with Intel Core i5, 15.6-inch Full HD display, and comfortable keyboard. Great value for students and professionals.",
    specifications: {
      "Display": "15.6\" Full HD, 120Hz",
      "Processor": "Intel Core i5-1235U",
      "RAM": "8GB DDR4",
      "Storage": "256GB NVMe SSD",
      "Graphics": "Intel Iris Xe",
      "Battery": "Up to 7 hours",
      "OS": "Windows 11 Home",
      "Weight": "1.65 kg",
      "Color": "Carbon Black",
    },
    popular: true,
  },
  {
    id: "lp-004",
    name: "HP 240 G9 Notebook",
    brand: "HP",
    model: "240 G9",
    category: "laptops",
    subcategory: "Business",
    ram: "4GB",
    storage: "256GB SSD",
    color: "Silver",
    price: 320000,
    image: img("https://images.pexels.com/photos/12200696/pexels-photo-12200696.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/12200696/pexels-photo-12200696.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The HP 240 G9 is an affordable business notebook with Intel Core i3, 14-inch display, and essential connectivity. Lightweight and portable for on-the-go productivity.",
    specifications: {
      "Display": "14\" HD, 220 nits",
      "Processor": "Intel Core i3-1215U",
      "RAM": "4GB DDR4",
      "Storage": "256GB SSD",
      "Graphics": "Intel UHD Graphics",
      "Battery": "Up to 6 hours",
      "OS": "Windows 11 Pro",
      "Weight": "1.41 kg",
      "Color": "Silver",
    },
  },
  {
    id: "lp-005",
    name: "Lenovo IdeaPad Slim 3",
    brand: "Lenovo",
    model: "15IAH8",
    category: "laptops",
    subcategory: "Budget",
    ram: "8GB",
    storage: "512GB SSD",
    color: "Arctic Grey",
    price: 450000,
    image: img("https://images.pexels.com/photos/11982694/pexels-photo-11982694.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/11982694/pexels-photo-11982694.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The Lenovo IdeaPad Slim 3 features an Intel Core i5 processor, 15.6-inch Full HD display, and slim design. Perfect balance of performance and portability.",
    specifications: {
      "Display": "15.6\" Full HD, 300 nits",
      "Processor": "Intel Core i5-1235U",
      "RAM": "8GB DDR4",
      "Storage": "512GB NVMe SSD",
      "Graphics": "Intel Iris Xe",
      "Battery": "Up to 7 hours",
      "OS": "Windows 11 Home",
      "Weight": "1.62 kg",
      "Color": "Arctic Grey",
    },
    new: true,
  },
  {
    id: "lp-006",
    name: "ASUS VivoBook 15",
    brand: "ASUS",
    model: "X1504VA",
    category: "laptops",
    subcategory: "Budget",
    ram: "8GB",
    storage: "512GB SSD",
    color: "Quiet Blue",
    price: 480000,
    image: img("https://images.pexels.com/photos/7792775/pexels-photo-7792775.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/7792775/pexels-photo-7792775.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The ASUS VivoBook 15 combines style and performance with Intel Core i5, 15.6-inch Full HD display, and a backlit keyboard. Thin and light for everyday computing.",
    specifications: {
      "Display": "15.6\" Full HD, 250 nits",
      "Processor": "Intel Core i5-1335U",
      "RAM": "8GB DDR4",
      "Storage": "512GB NVMe SSD",
      "Graphics": "Intel Iris Xe",
      "Battery": "Up to 8 hours",
      "OS": "Windows 11 Home",
      "Weight": "1.66 kg",
      "Color": "Quiet Blue",
    },
  },

  // ===== AUDIO =====
  {
    id: "au-001",
    name: "Sony WH-1000XM5 Wireless Headphones",
    brand: "Sony",
    model: "WH-1000XM5",
    category: "audio",
    subcategory: "Headphones",
    color: "Black",
    price: 285000,
    oldPrice: 320000,
    image: img("https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
      img("https://images.pexels.com/photos/3394648/pexels-photo-3394648.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
      img("https://images.pexels.com/photos/3394653/pexels-photo-3394653.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "Industry-leading noise cancellation with the Sony WH-1000XM5. Featuring 8 microphones, 30-hour battery life, and exceptional sound quality with LDAC support.",
    specifications: {
      "Type": "Over-ear, Wireless",
      "Noise Cancelling": "Yes, Adaptive",
      "Battery Life": "30 hours (ANC on)",
      "Charging": "USB-C, 3 min = 3 hours",
      "Bluetooth": "5.2",
      "Codecs": "LDAC, AAC, SBC",
      "Weight": "250g",
      "Color": "Black",
    },
    featured: true,
    popular: true,
  },
  {
    id: "au-002",
    name: "Sony WH-1000XM5 Wireless Headphones",
    brand: "Sony",
    model: "WH-1000XM5",
    category: "audio",
    subcategory: "Headphones",
    color: "White",
    price: 285000,
    image: img("https://images.pexels.com/photos/3394653/pexels-photo-3394653.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/3394653/pexels-photo-3394653.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
      img("https://images.pexels.com/photos/3394651/pexels-photo-3394651.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The white variant of Sony's flagship WH-1000XM5 headphones. Industry-leading noise cancellation, 30-hour battery, and premium sound in an elegant white finish.",
    specifications: {
      "Type": "Over-ear, Wireless",
      "Noise Cancelling": "Yes, Adaptive",
      "Battery Life": "30 hours (ANC on)",
      "Charging": "USB-C",
      "Bluetooth": "5.2",
      "Codecs": "LDAC, AAC, SBC",
      "Weight": "250g",
      "Color": "White",
    },
    popular: true,
  },
  {
    id: "au-003",
    name: "JBL Tune 510BT Wireless Headphones",
    brand: "JBL",
    model: "JBLT510BTBLK",
    category: "audio",
    subcategory: "Headphones",
    color: "Black",
    price: 45000,
    image: img("https://images.pexels.com/photos/3394648/pexels-photo-3394648.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/3394648/pexels-photo-3394648.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "JBL Pure Bass sound with up to 40 hours of wireless playback. The Tune 510BT features a foldable design and multi-point connection for everyday listening.",
    specifications: {
      "Type": "On-ear, Wireless",
      "Battery Life": "40 hours",
      "Charging": "USB-C, 5 min = 2 hours",
      "Bluetooth": "5.0",
      "Weight": "160g",
      "Color": "Black",
    },
  },
  {
    id: "au-004",
    name: "Sony WF-C700N True Wireless Earbuds",
    brand: "Sony",
    model: "WF-C700N",
    category: "audio",
    subcategory: "Earbuds",
    color: "Black",
    price: 68000,
    image: img("https://images.pexels.com/photos/9956763/pexels-photo-9956763.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/9956763/pexels-photo-9956763.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "Compact true wireless earbuds with active noise cancellation, DSEE technology for enhanced sound, and up to 15 hours of battery life with the charging case.",
    specifications: {
      "Type": "True Wireless Earbuds",
      "Noise Cancelling": "Yes, ANC",
      "Battery Life": "10h + 10h (case), 15h total",
      "Charging": "USB-C",
      "Bluetooth": "5.2",
      "Water Resistance": "IPX4",
      "Weight": "4.6g per earbud",
      "Color": "Black",
    },
    new: true,
    popular: true,
  },
  {
    id: "au-005",
    name: "JBL Flip 6 Portable Speaker",
    brand: "JBL",
    model: "JBLFLIP6BLK",
    category: "audio",
    subcategory: "Speakers",
    color: "Black",
    price: 75000,
    image: img("https://images.pexels.com/photos/33298190/pexels-photo-33298190.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/33298190/pexels-photo-33298190.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
      img("https://images.pexels.com/photos/29581125/pexels-photo-29581125.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "Bold JBL Original Pro Sound in a portable package. The Flip 6 features a 2-way speaker system, IP67 waterproof design, and 12 hours of playtime.",
    specifications: {
      "Type": "Portable Bluetooth Speaker",
      "Battery Life": "12 hours",
      "Waterproof": "IP67",
      "Bluetooth": "5.1",
      "Charging": "USB-C",
      "Weight": "550g",
      "Color": "Black",
    },
    popular: true,
  },
  {
    id: "au-006",
    name: "JBL Charge 5 Portable Speaker",
    brand: "JBL",
    model: "JBLCHARGE5BLK",
    category: "audio",
    subcategory: "Speakers",
    color: "Black",
    price: 110000,
    image: img("https://images.pexels.com/photos/29581125/pexels-photo-29581125.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/29581125/pexels-photo-29581125.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "Powerful JBL Pro Sound with a built-in powerbank. The Charge 5 delivers 20 hours of playtime, IP67 waterproof rating, and can charge your devices via USB.",
    specifications: {
      "Type": "Portable Bluetooth Speaker",
      "Battery Life": "20 hours",
      "Waterproof": "IP67",
      "Bluetooth": "5.1",
      "Charging": "USB-C, Powerbank feature",
      "Weight": "960g",
      "Color": "Black",
    },
  },

  // ===== WEARABLES =====
  {
    id: "wr-001",
    name: "Apple Watch Series 9",
    brand: "Apple",
    model: "MR8U3LL/A",
    category: "wearables",
    subcategory: "Smartwatches",
    color: "Midnight Aluminum",
    price: 420000,
    oldPrice: 460000,
    image: img("https://images.pexels.com/photos/12564670/pexels-photo-12564670.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/12564670/pexels-photo-12564670.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
      img("https://images.pexels.com/photos/11677077/pexels-photo-11677077.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The Apple Watch Series 9 features the S9 chip, a brighter Always-On Retina display, Double Tap gesture, and advanced health sensors including ECG, blood oxygen, and temperature sensing.",
    specifications: {
      "Display": "45mm Always-On Retina LTPO3 OLED",
      "Processor": "S9 SiP",
      "Storage": "64GB",
      "Health Sensors": "ECG, Blood Oxygen, Temperature",
      "Water Resistance": "50m",
      "Battery": "Up to 18 hours",
      "Connectivity": "GPS + Cellular",
      "Color": "Midnight Aluminum",
    },
    featured: true,
    popular: true,
  },
  {
    id: "wr-002",
    name: "Samsung Galaxy Watch 6",
    brand: "Samsung",
    model: "SM-R940",
    category: "wearables",
    subcategory: "Smartwatches",
    color: "Graphite",
    price: 280000,
    image: img("https://images.pexels.com/photos/11677077/pexels-photo-11677077.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/11677077/pexels-photo-11677077.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The Galaxy Watch 6 features a larger, brighter Super AMOLED display, advanced sleep coaching, body composition tracking, and a customizable bezel for navigation.",
    specifications: {
      "Display": "1.5\" Super AMOLED, 425x425",
      "Processor": "Exynos W930",
      "Storage": "16GB",
      "Health Sensors": "Heart Rate, ECG, BIA",
      "Water Resistance": "5ATM + IP68",
      "Battery": "425mAh",
      "OS": "Wear OS 4",
      "Color": "Graphite",
    },
    popular: true,
  },
  {
    id: "wr-003",
    name: "Oraimo Watch 2 Pro",
    brand: "Oraimo",
    model: "OSW-02P",
    category: "wearables",
    subcategory: "Smartwatches",
    color: "Black",
    price: 38000,
    image: img("https://images.pexels.com/photos/31541678/pexels-photo-31541678.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/31541678/pexels-photo-31541678.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "Affordable smartwatch with 1.8-inch HD display, SpO2 monitoring, heart rate tracking, and 7-day battery life. Compatible with iOS and Android.",
    specifications: {
      "Display": "1.8\" HD",
      "Health Sensors": "Heart Rate, SpO2",
      "Water Resistance": "IP68",
      "Battery": "7 days typical use",
      "Compatibility": "iOS 12+ / Android 6+",
      "Color": "Black",
    },
  },

  // ===== TABLETS =====
  {
    id: "tb-001",
    name: "Samsung Galaxy Tab S9 FE",
    brand: "Samsung",
    model: "SM-X510",
    category: "tablets",
    ram: "8GB",
    storage: "256GB",
    color: "Mint",
    price: 580000,
    image: img("https://images.pexels.com/photos/18205642/pexels-photo-18205642.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/18205642/pexels-photo-18205642.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
      img("https://images.pexels.com/photos/33125886/pexels-photo-33125886.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The Galaxy Tab S9 FE features a 10.9-inch display, S Pen included, Exynos 1380 processor, and IP68 water resistance. Perfect for creativity and entertainment.",
    specifications: {
      "Display": "10.9\" WQXGA TFT, 90Hz",
      "Processor": "Exynos 1380",
      "RAM": "8GB",
      "Storage": "256GB",
      "Camera": "12MP rear, 8MP front",
      "Battery": "8000mAh",
      "OS": "Android 13, One UI 5.1",
      "S Pen": "Included",
      "Color": "Mint",
    },
    featured: true,
  },
  {
    id: "tb-002",
    name: "Apple iPad 10th Generation",
    brand: "Apple",
    model: "MQ5J3LL/A",
    category: "tablets",
    storage: "256GB",
    color: "Silver",
    price: 620000,
    image: img("https://images.pexels.com/photos/33125886/pexels-photo-33125886.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/33125886/pexels-photo-33125886.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The redesigned iPad 10 features a 10.9-inch Liquid Retina display, A14 Bionic chip, USB-C, and works with the Apple Pencil (1st gen). Perfect for everyday tasks and creativity.",
    specifications: {
      "Display": "10.9\" Liquid Retina, 500 nits",
      "Processor": "A14 Bionic",
      "Storage": "256GB",
      "Camera": "12MP rear, 12MP front",
      "Battery": "Up to 10 hours",
      "OS": "iPadOS 17",
      "Connectivity": "USB-C, Wi-Fi 6",
      "Color": "Silver",
    },
    popular: true,
  },
  {
    id: "tb-003",
    name: "Samsung Galaxy Tab A9+",
    brand: "Samsung",
    model: "SM-X210",
    category: "tablets",
    ram: "4GB",
    storage: "64GB",
    color: "Graphite",
    price: 220000,
    image: img("https://images.pexels.com/photos/17803200/pexels-photo-17803200.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/17803200/pexels-photo-17803200.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The Galaxy Tab A9+ offers an 11-inch display, Snapdragon 695, quad speakers with Dolby Atmos, and Samsung DeX for a desktop-like experience.",
    specifications: {
      "Display": "11\" TFT, 90Hz",
      "Processor": "Snapdragon 695",
      "RAM": "4GB",
      "Storage": "64GB",
      "Camera": "8MP rear, 5MP front",
      "Battery": "7040mAh",
      "OS": "Android 13, One UI 5.1",
      "Color": "Graphite",
    },
  },

  // ===== CAMERAS =====
  {
    id: "cm-001",
    name: "Sony Alpha A7 IV Mirrorless Camera",
    brand: "Sony",
    model: "ILCE-7M4",
    category: "cameras",
    subcategory: "Mirrorless",
    color: "Black",
    price: 3200000,
    oldPrice: 3500000,
    image: img("https://images.pexels.com/photos/28859522/pexels-photo-28859522.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/28859522/pexels-photo-28859522.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
      img("https://images.pexels.com/photos/16013967/pexels-photo-16013967.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The Sony A7 IV is a hybrid full-frame camera with 33MP sensor, 4K 60p video, real-time autofocus, and a vari-angle touchscreen. The perfect balance of photo and video performance.",
    specifications: {
      "Sensor": "33MP Full-Frame Exmor R",
      "Video": "4K 60p, 10-bit 4:2:2",
      "ISO": "100-51200",
      "Autofocus": "759 phase-detection points",
      "Screen": "3\" vari-angle touchscreen",
      "Stabilization": "5-axis in-body",
      "Storage": "CFexpress Type A + SD",
      "Color": "Black",
    },
    featured: true,
  },
  {
    id: "cm-002",
    name: "Nikon D7500 DSLR Camera",
    brand: "Nikon",
    model: "D7500",
    category: "cameras",
    subcategory: "DSLR",
    color: "Black",
    price: 1250000,
    image: img("https://images.pexels.com/photos/10416279/pexels-photo-10416279.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/10416279/pexels-photo-10416279.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
      img("https://images.pexels.com/photos/26292003/pexels-photo-26292003.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The Nikon D7500 features a 20.9MP DX-format sensor, 4K UHD video, 8 fps continuous shooting, and a rugged weather-sealed body. A versatile DSLR for enthusiasts.",
    specifications: {
      "Sensor": "20.9MP DX-format CMOS",
      "Video": "4K UHD 30p",
      "ISO": "100-51200",
      "Autofocus": "51-point AF system",
      "Screen": "3.2\" tilting touchscreen",
      "Continuous Shooting": "8 fps",
      "Storage": "SDXC",
      "Color": "Black",
    },
    popular: true,
  },
  {
    id: "cm-003",
    name: "Fujifilm X-T30 II Mirrorless Camera",
    brand: "Fujifilm",
    model: "X-T30 II",
    category: "cameras",
    subcategory: "Mirrorless",
    color: "Black",
    price: 980000,
    image: img("https://images.pexels.com/photos/33037156/pexels-photo-33037156.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/33037156/pexels-photo-33037156.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The Fujifilm X-T30 II combines a 26.1MP X-Trans IV sensor with classic film simulations, 4K 30p video, and a compact retro design. Perfect for street and travel photography.",
    specifications: {
      "Sensor": "26.1MP X-Trans CMOS IV",
      "Video": "4K 30p, 10-bit",
      "ISO": "160-12800",
      "Autofocus": "425-point hybrid AF",
      "Screen": "3\" tilting touchscreen",
      "Continuous Shooting": "8 fps mechanical",
      "Film Simulations": "18 modes",
      "Color": "Black",
    },
    new: true,
  },
  {
    id: "cm-004",
    name: "Canon EOS R50 Mirrorless Camera",
    brand: "Canon",
    model: "EOS R50",
    category: "cameras",
    subcategory: "Mirrorless",
    color: "Black",
    price: 720000,
    image: img("https://images.pexels.com/photos/19792413/pexels-photo-19792413.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/19792413/pexels-photo-19792413.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The Canon EOS R50 is a lightweight mirrorless camera with 24.2MP APS-C sensor, 4K 30p video, and Dual Pixel CMOS AF II. Ideal for content creators and beginners.",
    specifications: {
      "Sensor": "24.2MP APS-C CMOS",
      "Video": "4K 30p, FHD 120p",
      "ISO": "100-32000",
      "Autofocus": "Dual Pixel CMOS AF II",
      "Screen": "3\" vari-angle touchscreen",
      "Continuous Shooting": "12 fps electronic",
      "Weight": "375g (body only)",
      "Color": "Black",
    },
  },

  // ===== GAMING =====
  {
    id: "gm-001",
    name: "PlayStation 5 DualSense Controller",
    brand: "PlayStation",
    model: "CFI-ZCT1W",
    category: "gaming",
    subcategory: "Controllers",
    color: "White",
    price: 65000,
    image: img("https://images.pexels.com/photos/16070479/pexels-photo-16070479.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/16070479/pexels-photo-16070479.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The DualSense wireless controller offers immersive haptic feedback, adaptive triggers, a built-in microphone, and a create button. The signature PS5 controller experience.",
    specifications: {
      "Platform": "PlayStation 5",
      "Connectivity": "Bluetooth, USB-C",
      "Features": "Haptic feedback, Adaptive triggers",
      "Battery": "Built-in rechargeable",
      "Microphone": "Built-in",
      "Color": "White",
    },
    popular: true,
  },
  {
    id: "gm-002",
    name: "Xbox Wireless Controller",
    brand: "Xbox",
    model: "QAS-00002",
    category: "gaming",
    subcategory: "Controllers",
    color: "Robot White",
    price: 52000,
    image: img("https://images.pexels.com/photos/6962206/pexels-photo-6962206.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/6962206/pexels-photo-6962206.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
      img("https://images.pexels.com/photos/14642112/pexels-photo-14642112.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The Xbox Wireless Controller features textured grips, a hybrid D-pad, and seamless compatibility with Xbox Series X|S, Xbox One, and Windows PC. Share button for instant capture.",
    specifications: {
      "Platform": "Xbox Series X|S, Xbox One, PC",
      "Connectivity": "Xbox Wireless, Bluetooth, USB-C",
      "Features": "Textured grip, Hybrid D-pad, Share button",
      "Battery": "AA batteries or rechargeable",
      "Color": "Robot White",
    },
  },
  {
    id: "gm-003",
    name: "Logitech F710 Wireless Gamepad",
    brand: "Logitech",
    model: "940-000117",
    category: "gaming",
    subcategory: "Controllers",
    color: "Black",
    price: 38000,
    image: img("https://images.pexels.com/photos/4225230/pexels-photo-4225230.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/4225230/pexels-photo-4225230.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The Logitech F710 is a wireless gamepad with vibration feedback, XInput/DirectInput modes, and a console-style layout. Compatible with Windows PC games.",
    specifications: {
      "Platform": "Windows PC",
      "Connectivity": "2.4GHz wireless USB nano-receiver",
      "Features": "Dual vibration motors",
      "Battery": "2x AA",
      "Color": "Black",
    },
  },
  {
    id: "gm-004",
    name: "ASUS ROG Gaming Mouse",
    brand: "ASUS",
    model: "ROG Gladius II",
    category: "gaming",
    subcategory: "Gaming Mouse",
    color: "Black",
    price: 45000,
    image: img("https://images.pexels.com/photos/32890143/pexels-photo-32890143.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/32890143/pexels-photo-32890143.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The ROG Gladius II features a 12000 DPI optical sensor, customizable RGB lighting, swappable Omron switches, and an ergonomic design for competitive gaming.",
    specifications: {
      "Sensor": "12000 DPI Optical",
      "Buttons": "6 programmable",
      "Connectivity": "Wired USB",
      "RGB": "Aura Sync RGB",
      "Weight": "110g",
      "Color": "Black",
    },
    new: true,
  },

  // ===== TV & DISPLAYS =====
  {
    id: "tv-001",
    name: "LG 43-inch 4K UHD Smart TV",
    brand: "LG",
    model: "43UR8050",
    category: "tv",
    subcategory: "Smart TV",
    color: "Black",
    price: 380000,
    oldPrice: 420000,
    image: img("https://images.pexels.com/photos/28195649/pexels-photo-28195649.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/28195649/pexels-photo-28195649.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
      img("https://images.pexels.com/photos/9646752/pexels-photo-9646752.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "LG 43UR8050 4K UHD Smart TV with webOS 23, AI ThinQ, Active HDR, and a sleek bezel-less design. Stream your favorite content with built-in apps.",
    specifications: {
      "Screen Size": "43 inches",
      "Resolution": "4K UHD (3840 x 2160)",
      "Panel": "LED",
      "Smart Platform": "webOS 23, AI ThinQ",
      "HDR": "Active HDR / HDR10",
      "Refresh Rate": "60Hz",
      "Ports": "3x HDMI, 1x USB, Optical",
      "Color": "Black",
    },
    featured: true,
  },
  {
    id: "tv-002",
    name: "LG 50-inch 4K UHD Smart TV",
    brand: "LG",
    model: "50UR8050",
    category: "tv",
    subcategory: "Smart TV",
    color: "Black",
    price: 450000,
    image: img("https://images.pexels.com/photos/9646752/pexels-photo-9646752.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/9646752/pexels-photo-9646752.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The 50-inch LG 4K UHD Smart TV delivers stunning picture quality with AI Picture Pro, webOS 23, and a bezel-less design for an immersive viewing experience.",
    specifications: {
      "Screen Size": "50 inches",
      "Resolution": "4K UHD (3840 x 2160)",
      "Panel": "LED",
      "Smart Platform": "webOS 23, AI ThinQ",
      "HDR": "Active HDR / HDR10",
      "Refresh Rate": "60Hz",
      "Ports": "3x HDMI, 1x USB, Optical",
      "Color": "Black",
    },
    popular: true,
  },
  {
    id: "tv-003",
    name: "LG 27-inch 4K UHD Monitor",
    brand: "LG",
    model: "27UQ850-W",
    category: "tv",
    subcategory: "Monitors",
    color: "White",
    price: 320000,
    image: img("https://images.pexels.com/photos/5552789/pexels-photo-5552789.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/5552789/pexels-photo-5552789.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "LG 27-inch 4K UHD IPS monitor with 98% DCI-P3 color gamut, USB-C 90W charging, and ergonomic stand. Perfect for creative professionals and productivity.",
    specifications: {
      "Screen Size": "27 inches",
      "Resolution": "4K UHD (3840 x 2160)",
      "Panel": "IPS",
      "Refresh Rate": "60Hz",
      "Color Gamut": "98% DCI-P3",
      "Ports": "USB-C 90W, 2x HDMI, DisplayPort",
      "Stand": "Height/tilt/pivot adjustable",
      "Color": "White",
    },
  },

  // ===== ACCESSORIES =====
  {
    id: "ac-001",
    name: "Anker PowerCore 20000 PD Power Bank",
    brand: "Anker",
    model: "A1261",
    category: "accessories",
    subcategory: "Power Banks",
    color: "Black",
    price: 38000,
    image: img("https://images.pexels.com/photos/38649173/pexels-photo-38649173.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/38649173/pexels-photo-38649173.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "High-capacity 20000mAh power bank with 20W USB-C Power Delivery. Charge phones up to 5 times and tablets up to 2 times. Compact design with Anker's MultiProtect safety system.",
    specifications: {
      "Capacity": "20000mAh",
      "Output": "USB-C 20W PD, USB-A 18W",
      "Input": "USB-C 20W",
      "Weight": "356g",
      "Color": "Black",
    },
    popular: true,
  },
  {
    id: "ac-002",
    name: "Anker 20W USB-C Fast Charger",
    brand: "Anker",
    model: "A2632",
    category: "accessories",
    subcategory: "Chargers",
    color: "White",
    price: 12000,
    image: img("https://images.pexels.com/photos/947407/pexels-photo-947407.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/947407/pexels-photo-947407.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "Compact 20W USB-C wall charger with Power Delivery. Charges iPhone and Android devices up to 3x faster than standard 5W chargers. Foldable plug design.",
    specifications: {
      "Output": "20W USB-C PD",
      "Input": "100-240V AC",
      "Compatibility": "iPhone, Samsung, Google, more",
      "Weight": "50g",
      "Color": "White",
    },
  },
  {
    id: "ac-003",
    name: "Logitech MK270 Wireless Keyboard & Mouse",
    brand: "Logitech",
    model: "920-004536",
    category: "accessories",
    subcategory: "Keyboard & Mouse",
    color: "Black",
    price: 28000,
    image: img("https://images.pexels.com/photos/8219211/pexels-photo-8219211.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/8219211/pexels-photo-8219211.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "The Logitech MK270 combo includes a wireless keyboard and mouse with a single USB nano-receiver. Spill-resistant design, 24-month keyboard battery, and 12-month mouse battery.",
    specifications: {
      "Connection": "2.4GHz wireless USB receiver",
      "Keyboard Battery": "24 months (2x AAA)",
      "Mouse Battery": "12 months (1x AA)",
      "Range": "10 meters",
      "Color": "Black",
    },
  },
  {
    id: "ac-004",
    name: "Logitech G Pro Mechanical Keyboard",
    brand: "Logitech",
    model: "920-009270",
    category: "accessories",
    subcategory: "Keyboard & Mouse",
    color: "Black",
    price: 75000,
    image: img("https://images.pexels.com/photos/18311171/pexels-photo-18311171.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/18311171/pexels-photo-18311171.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "Tenkeyless mechanical gaming keyboard with GX Blue switches, customizable RGB lighting, and a detachable USB-C cable. Built for competitive gaming with a compact footprint.",
    specifications: {
      "Switches": "GX Blue Tactile Clicky",
      "Layout": "Tenkeyless (TKL)",
      "Backlight": "Per-key RGB, LIGHTSYNC",
      "Connectivity": "USB-C detachable",
      "Key Rollover": "N-key rollover",
      "Color": "Black",
    },
    new: true,
  },
  {
    id: "ac-005",
    name: "Oraimo 10000mAh Power Bank",
    brand: "Oraimo",
    model: "OPB-P1001",
    category: "accessories",
    subcategory: "Power Banks",
    color: "Black",
    price: 18000,
    image: img("https://images.pexels.com/photos/18641665/pexels-photo-18641665.png?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/18641665/pexels-photo-18641665.png?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "Slim 10000mAh power bank with dual USB outputs, fast charging support, and LED battery indicator. Reliable backup power for your devices on the go.",
    specifications: {
      "Capacity": "10000mAh",
      "Output": "2x USB-A, 1x micro-USB input",
      "Weight": "230g",
      "Color": "Black",
    },
  },
  {
    id: "ac-006",
    name: "Anker 622 Magnetic Wireless Charger",
    brand: "Anker",
    model: "A1611",
    category: "accessories",
    subcategory: "Chargers",
    color: "Black",
    price: 28000,
    image: img("https://images.pexels.com/photos/4765366/pexels-photo-4765366.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    images: [
      img("https://images.pexels.com/photos/4765366/pexels-photo-4765366.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"),
    ],
    inStock: true,
    description: "Magnetic wireless battery pack for iPhone 12 and newer. Snaps perfectly onto the back of your phone for 5000mAh of wireless charging on the go. Foldable kickstand included.",
    specifications: {
      "Capacity": "5000mAh",
      "Output": "7.5W magnetic wireless",
      "Compatibility": "iPhone 12 series and newer",
      "Weight": "130g",
      "Color": "Black",
    },
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, limit);
}

export function formatPrice(price: number): string {
  return "₦" + price.toLocaleString("en-NG");
}
